apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: edu-goods-hpa
  namespace: edu-goods  # 배포가 있는 네임스페이스
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-edu-goods-deployment  # Autoscaler가 적용될 배포 이름
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30  # CPU 사용률 50%를 목표로 설정
