apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-edu-user-deployment
  namespace: edu-user
spec:
  selector:
    matchLabels:
      app: k8s-edu-user-app
  template:
    metadata:
      labels:
        app: k8s-edu-user-app
        version: blue
    spec:
      containers:
        - name: k8s-edu-user-app
          image: chxmi/k8s-edu:v0.0.10          # dockerhub image repository : repo/image명:Tag
          imagePullPolicy: IfNotPresent        # k8s 클러스터에 다운로드 된 이미지 없으면 다운 or Always
          ports:
            - name: http
              containerPort: 8080              # demo.jar 실행 포트
              protocol: TCP
          resources:                           # pod 사용 리소스 설정 블록
            requests:                          # 생성시 필요한 최소 리소스
              cpu: "1"
              memory: "2Gi"
            limits:                            # pod가 사용 가능한 최대 리소스
              cpu: "1"
              memory: "2Gi"
          env:                                 # pod 내 환경 변수 설정
            - name: SPRING_PROFILES_ACTIVE     # spring profile 설정
              value: prod                      # 상용(prod) 환경
            - name: GOODS_API_URL
              valueFrom:
                configMapKeyRef:
                  name: edu-user-config
                  key: GOODS_API_URL
          livenessProbe:
            httpGet:
              path: /api/v1/user/   # 상태 체크할 경로
              port: 8080       # 서비스 포트
            initialDelaySeconds: 10  # 처음 시작 후 기다리는 시간 (초)
            periodSeconds: 5         # 상태 체크 간격 (초)
            failureThreshold: 3      # 실패한 횟수
            successThreshold: 1      # 성공한 횟수
      imagePullSecrets:                        # dockerhub 이미지 pull 위한 secret
        - name: k8s-edu-dockerhub-secret
